#!/usr/bin/env node
'use strict';

const program = require('commander');

program
    .version('1.0.0')
    .command('to-jira <input> <output>', 'Converts a Trello JSON (input) into a Jira JSON (output).').alias('j')
    .parse(process.argv);

if (program.args.length === 0) {
    program.help();
}